{{- if .Values.persistence.customStorageClass -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.persistence.storageClassName }}
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
provisioner: {{ .Values.persistence.storageProvisioner | quote }}
parameters:
  {{- toYaml .Values.persistence.storageParameters | nindent 2 }}
{{- end -}}
